### ISSUE TITLE
Este vagrant del c....!!!

### ISSUE THREAD

**Issue by em-torres** [Eduardoveras94/RocketMD#7]
## Expected behavior.
Ok, Tengo problemas al tratar de *setear* el bootstrap.sh de vagrant para correrlo con *vagrant up*. Otra opcion es tratar de crear la maquina virtual, dar un *vagrant package* (empaqueta la maquina virtual en alrededor 700MB) se sube a un server y todo el mundo lo tiene.

Si alguien tiene alguna otra idea o sugerencia me avisan.

**Comment by Eduardoveras94** [comment]
Porque no seteas el enviroment en tu pc local y ya ? xD vagrant no es tan urgente ahora mismo, podemos hacer un script que cree el enviroment
